### ISSUE TITLE
Fill in gaps in test coverage and docstrings

### ISSUE THREAD

**Issue by aimalz** [LSSTDESC/rail_som#3]
There are a concerning number of `# pragma: no cover`s in `somocluSOM.py` that were added when somoclu's nonstandard installation instructions were causing problems for GitHub Actions. Now that the underlying problem has been solved, we should write those to ensure the smoke tests catch if the dependency breaks at some point in the future. Also some of the functions in there lack docstrings, so those should be filled in at the same time, to help future devs make modifications in response to anticipated changes in the dependencies.

**Comment by eacharles** [comment]
Let's save the bug label for things that are actually broken.
